### PR TITLE
Updated System Proposal

### PR DESCRIPTION
**Pull request by paulvazbad**
In this branch I will be commiting the changes to the diagram of the robot's software architecture. Discussion about this design is encouraged! Please add information regarding your teams' feature and how it connects to other ROS packages.

### Suggested TODOs:
- [x] Speech-To-Text Architecture
- [x] Main Engine (Main.py of the robot)
- [x] Navigation architecture
- [ ] Peripherals (Microphone, LCD Screen, Motor control board, Arm control board)
- [x]  Object Detection 

### How to view the design:

Download the .drawio file located in the root folder of the repo and open it in https://www.draw.io/
Screenshots may be provided in this pull request addressing comments made by the team.

### CODE REVIEW

**Comment by diegocardozo97** [comment]
I propose to standarize the names; that all the names of the nodes to be camel case capitalized "AnExampleOfNode", and the topics "an_example_of_topic". Then, the services to be "anExampleOfService".

**Comment by paulvazbad** [comment]
@diegocardozo97 do you want to change the name of any topic or node that you are using/publishing to?
This is the current proposal.
image

**Comment by diegocardozo97** [comment]
What do you think of these renamings? The idea will be to express that a "chunk" is "each incoming chunk of frames in real-time" and "fragment" is "an actual clip of audio".
I don't know about "user_sentence" and "parser". 

image

**Comment by paulvazbad** [comment]
Much more descriptive, I like it.

**Comment by paulvazbad** [comment]
This is the current state of the SystemDesign, only the Arm module and the communication with the arduino of the base are missing.
image

**Comment by diegocardozo97** [comment]
One change could be in the interface with object-detection module. The main idea would be to have a node for that, removing that from ACTION, and including the conection between it and navigation. This helps splitting the work and enable future things like fully integrating that to ROS.

There is missing a future input from the other cameras and an input from main_engine to tell the ObjectDetector node to which camera use, rate, etc.

image

**Comment by paulvazbad** [comment]
So an ActionKnight that is in charge of the object detection challenge is not necessary ? I think the thing that you are describing was considered to be an Action Knight, but in this case it would be running constantly.

**Comment by diegocardozo97** [comment]
The idea will be to have a complete node taking care of object detection's things and the main_engine only ordering and checking things.

**Comment by diegocardozo97** [comment]
Also, as we talked offline, let's try to at least enable a connection between SpeechSynthesizer and main_engine with the topic.

**Pull request merged**
