### PR TITLE
Support the Intel RealSense in ObjDetection and add 2 Algorithms Using the Depth

### PR DESCRIPTION
**Pull request by diegocardozo97**
Add support for using the Intel RealSense Camera in action_selectors/ObjectDetector.py and add two algorithms that using the depth computes more info of the framed objects.

- Add launch files to launch the RealSense Node together with the ObjectDetector.
- Add a flag to toggle between the normal camera and the RS.
- Add a function to render the image in ObjectDetector.py
- Add a segmentation algorithm of the detected objects that uses as guide the depth and computes the center and inclination angle.
- Add algorithm that guiding itself by the depth, detects the limits of the four sides of the objects.

This is useful in general as a good reference of how to interface and for understanding some key things of the camera. The algorithms are almost only prototype of ideas that usually work.
Sorry for the big delay, I hope this is useful. After this, I would make some minor additions to the wiki, share an email with Tomy, and I think that would be the most of the things I have about this. Maybe other info is very specific, but can add it later or answer if asked.

I don't have the camera any more... then I will strongly suggest that @tomvik test this to at least ensure "compiles", tell me if not to fix and add some images as evidence before merging this.

#40

### CODE REVIEW

**Review by paulvazbad — APPROVED** [review]

**Comment by tomvik** [comment]
I'm working on this. Currently I'm having some issues with running Alexis' part. However, once its fixed it will probably be good to merge.

**Review by tomvik — APPROVED** [review]
I'd say LGTM, but I also did some changes at the end that may need some review from either of you @paulvazbad @diegocardozo97 .

Let's keep in mind that there's a lot of work to do forward, but this definitely helps a lot. Thank you Cardozo!

**Comment by tomvik** [comment]
@diegocardozo97 @paulvazbad ping for a LGTM to merge this.

**Comment by paulvazbad** [comment]
Yeah, I have approved this :) LGTM thank you @diegocardozo97 .

**Pull request merged**
