### PR TITLE
Add in .gitignore to ignore .pyc and .vscode/

### PR DESCRIPTION
**Pull request by diegocardozo97**
Add in the file .gitignore to ignore the files with extension ".pyc" and directories ".vscode". The first ones are sometimes automatically created when running python code, and the second ones are created to store configuration of the vscode editor.

Note that I looked for files of this type to remove all of them before this change to avoid leaving any forgoten in the repo. Then, I think is safe to start ignoring them.

### CODE REVIEW

**Comment by SAlexisvf** [comment]
Sure, and I think we should also ignore the `.vscode` folders.

**Comment by diegocardozo97** [comment]
True, I already deleted the `.vscode` folder and added to the .gitignore that directory.

**Comment by diegocardozo97** [comment]
Thanks, I deleted another .vscode folder that was left and I already updated the descriptions and title of the pull request.

**Comment by diegocardozo97** [comment]
Wait, I believe that also the directory .catkin_tools and maybe file .catkin_workspace, that are inside catkin_home, should neither be commited and can be added to the .gitignore and deleted from the repo. What do you think @SAlexisvf @paulvazbad ?

**Comment by paulvazbad** [comment]
I agree, we should just remember to build the workspace locally to generate them.

**Pull request merged**
